version: "2"

networks:
  dev-net:
    external:
      name: karna-dev-net

services:
  karna-org1-ca-server:
    container_name: karna-org1-ca-server
    image: msassone/karna-org1-ca-server:latest
    networks:
      dev-net:
        ipv4_address: 172.20.0.12
    volumes:
      - ../../../../karna/volumes/org1/host1/ca-msp:/etc/hyperledger/fabric-ca-server
      - ../../../../karna/volumes/org1/host1/ca-admin-msp:/etc/hyperledger/fabric-ca-client/admin/msp
      - ../../../../karna/volumes/org1/root-ca:/shared
    ports:
      - 7054:7054