version: "2"

networks:
  dev-net:
    external:
      name: karna-dev-net

services:
  karna-tls-ca-server:
    container_name: karna-tls-ca-server
    image: msassone/karna-tls-ca-server:latest
    networks:
      dev-net:
        ipv4_address: 172.20.0.10
    volumes:
      - ../../../karna/volumes/tls/ca-msp:/etc/hyperledger/fabric-ca-server
      - ../../../karna/volumes/tls/ca-admin-msp:/etc/hyperledger/fabric-ca-client/admin/msp
      - ../../../karna/volumes/tls/root-ca:/shared
    ports:
      - 7052:7052
