version: "2"

networks:
  dev-net:
    external:
      name: karna-dev-net

services:
  karna-tls-ca-client:
    container_name: karna-tls-ca-client
    image: msassone/karna-tls-ca-client:latest
    networks:
      dev-net:
        ipv4_address: 172.20.0.20
    volumes:
      - ../../../karna/volumes/tls/ca-admin-msp:/root/fabric-ca-client/tls-ca/admin/msp
      - ../../../karna/volumes/tls/root-ca:/root-ca/tls

