version: "2"

networks:
  dev-net:
    external:
      name: karna-dev-net

services:
  karna-org0-ca-server:
    container_name: karna-org0-ca-server
    image: msassone/karna-org0-ca-server:latest
    networks:
      dev-net:
        ipv4_address: 172.20.0.11
    volumes:
      - ../../../../karna/volumes/org0/host1/ca-msp:/etc/hyperledger/fabric-ca-server
      - ../../../../karna/volumes/org0/host1/ca-admin-msp:/etc/hyperledger/fabric-ca-client/admin/msp
      - ../../../../karna/volumes/org0/root-ca:/shared
    ports:
      - 7053:7053
